import type { ArticleTranslation } from "@/content/articles";

/** Bản dịch sẵn cho 9 bài seed (để demo đa ngôn ngữ). Admin có thể sửa trong form bài viết. */
export const SEED_TRANSLATIONS: Record<string, Record<"vi" | "en" | "ne", ArticleTranslation>> = {
  "ryugakusei-voice-2026": {
    vi: { title: "Tiếng nói nhân lực Nepal tại hiện trường điều dưỡng", excerpt: "Phỏng vấn nhân lực Nepal diện kỹ năng đặc định đang làm việc tại cơ sở điều dưỡng.", lead: "Học tiếng Nhật và điều dưỡng cơ bản, nhân lực Nepal đang tỏa sáng tại các cơ sở. Lắng nghe tâm sự của họ.", body: [{ type: "p", text: "Sau khi hoàn thành đào tạo tiếng Nhật và điều dưỡng cơ bản tại Nepal, bạn đã sang Nhật theo diện kỹ năng đặc định và hiện làm việc tại một cơ sở ở vùng Kanto." }, { type: "quote", text: "Khoảnh khắc được người sử dụng nói 'cảm ơn' là điều hạnh phúc nhất." }, { type: "p", text: "Momokichi và ITM Japan đồng hành để nhân lực yên tâm gắn bó lâu dài." }] },
    en: { title: "Voices of Nepali care workers on the frontline", excerpt: "Interviews with Specified Skilled Worker care staff from Nepal working at facilities.", lead: "Having studied Japanese and basic care, Nepali staff are thriving at facilities. We listened to their thoughts.", body: [{ type: "p", text: "After completing Japanese and basic care training in Nepal, the staff came to Japan as a Specified Skilled Worker and now works at a facility in the Kanto region." }, { type: "quote", text: "Being told 'thank you' by residents is the happiest moment." }, { type: "p", text: "Momokichi and ITM Japan walk alongside talent so they can work with peace of mind for the long term." }] },
    ne: { title: "स्याहार क्षेत्रमा नेपाली जनशक्तिको आवाज", excerpt: "केन्द्रमा कार्यरत विशेष दक्षता (स्याहार) का नेपाली कर्मचारीसँगको अन्तर्वार्ता।", lead: "जापानी र स्याहार आधारभूत सिकेर नेपाली कर्मचारी केन्द्रमा चम्किरहेका छन्। उनीहरूको मनको कुरा सुन्यौं।", body: [{ type: "p", text: "नेपालमा जापानी र स्याहार आधारभूत तालिम सकेर विशेष दक्षताका रूपमा जापान आई हाल कान्तो क्षेत्रको केन्द्रमा कार्यरत छन्।" }, { type: "quote", text: "सेवाग्राहीले 'धन्यवाद' भन्दा सबैभन्दा खुसी लाग्छ।" }, { type: "p", text: "Momokichi र ITM Japan ले जनशक्ति ढुक्कसँग दीर्घकालीन रूपमा काम गर्न सकून् भनेर साथ दिन्छन्।" }] },
  },
  "track-record-2026": {
    vi: { title: "Thành tích giới thiệu và tỷ lệ gắn bó đến nay", excerpt: "Số cơ quan phái cử, số nhân lực, tỷ lệ đỗ phỏng vấn, tỷ lệ gắn bó — qua các con số.", lead: "Giới thiệu hoạt động qua số liệu: cơ quan phái cử, số người, tỷ lệ đỗ và gắn bó.", body: [{ type: "p", text: "Đã giới thiệu lũy kế hơn 150 người, tỷ lệ đỗ phỏng vấn 95%, số cơ sở hợp tác hơn 30." }, { type: "p", text: "Nhờ chất lượng đào tạo tại chỗ và hỗ trợ định cư, chúng tôi duy trì tỷ lệ gắn bó cao." }] },
    en: { title: "Our placement record and retention so far", excerpt: "Sending organizations, placements, interview pass rate, retention — in numbers.", lead: "Our work in figures: partner sending organizations, people placed, pass and retention rates.", body: [{ type: "p", text: "We have placed over 150 people in total, with a 95% interview pass rate and more than 30 partner facilities." }, { type: "p", text: "With quality local training and post-arrival retention support, we maintain a high retention rate." }] },
    ne: { title: "अहिलेसम्मको परिचय उपलब्धि र टिकाउ दर", excerpt: "पठाउने संस्था, परिचय संख्या, अन्तर्वार्ता उत्तीर्ण दर, टिकाउ दर — सङ्ख्यामा।", lead: "तथ्याङ्कमा हाम्रो काम: साझेदार पठाउने संस्था, परिचय संख्या, उत्तीर्ण र टिकाउ दर।", body: [{ type: "p", text: "कुल १५० भन्दा बढी परिचय, अन्तर्वार्ता उत्तीर्ण दर ९५%, साझेदार केन्द्र ३० भन्दा बढी।" }, { type: "p", text: "स्थानीय तालिमको गुणस्तर र आगमनपछिको बसोबास सहयोगले उच्च टिकाउ दर कायम छ।" }] },
  },
  "interview-kanto-facility": {
    vi: { title: "Tiếng nói cơ sở tiếp nhận: Làn gió mới cho đội ngũ", excerpt: "Người phụ trách cơ sở chia sẻ về sự thay đổi tại hiện trường.", lead: "Chúng tôi hỏi người phụ trách cơ sở đã tiếp nhận nhân lực Nepal về thay đổi tại hiện trường.", body: [{ type: "p", text: "'Chăm chỉ, hiền lành, được người sử dụng tin tưởng' — lời của trưởng nhóm. Lo lắng trước khi tiếp nhận đã được giải tỏa nhờ đào tạo và hỗ trợ kỹ lưỡng." }, { type: "p", text: "Đội ngũ đa quốc gia giúp không khí nơi làm việc tươi sáng hơn." }] },
    en: { title: "Host facility's voice: A fresh wind for the team", excerpt: "A facility manager shares the changes on the ground.", lead: "We asked a manager at a facility that welcomed Nepali staff about the changes on site.", body: [{ type: "p", text: "'Diligent and kind, trusted by residents,' says the team leader. Pre-arrival concerns were resolved through careful training and support." }, { type: "p", text: "A multinational team has brightened the workplace atmosphere." }] },
    ne: { title: "स्वागत केन्द्रको आवाज: टोलीमा नयाँ हावा", excerpt: "केन्द्र प्रबन्धकले क्षेत्रको परिवर्तन साझा गर्छन्।", lead: "नेपाली कर्मचारी स्वागत गरेको केन्द्रका प्रबन्धकलाई क्षेत्रको परिवर्तनबारे सोध्यौं।", body: [{ type: "p", text: "'मेहनती र दयालु, सेवाग्राहीको विश्वास,' टोली नेताको भनाइ। स्वागतअघिको चिन्ता राम्रो तालिम र सहयोगले हट्यो।" }, { type: "p", text: "बहुराष्ट्रिय टोलीले कार्यस्थलको वातावरण उज्यालो बनाएको छ।" }] },
  },
  "jlpt-n4-support": {
    vi: { title: "Trình độ tiếng Nhật cần cho kỹ năng đặc định「điều dưỡng」", excerpt: "Giải thích yêu cầu tiếng Nhật (JLPT N4・JFT-Basic) và đào tạo tại chỗ.", lead: "Giải thích về JLPT N4・JFT-Basic và đào tạo tại nước sở tại.", body: [{ type: "p", text: "Diện kỹ năng đặc định「điều dưỡng」yêu cầu đạt N4 trở lên hoặc đỗ JFT-Basic." }, { type: "h2", text: "Nội dung đào tạo tại chỗ" }, { type: "p", text: "Cơ quan phái cử còn dạy thêm từ vựng chuyên ngành điều dưỡng để sẵn sàng làm việc ngay khi sang Nhật." }] },
    en: { title: "Japanese level required for Specified Skilled Worker (Care)", excerpt: "We explain the Japanese requirements (JLPT N4 / JFT-Basic) and local training.", lead: "An overview of JLPT N4 / JFT-Basic requirements and training in the home country.", body: [{ type: "p", text: "The Specified Skilled Worker (Care) status requires JLPT N4 or above, or passing JFT-Basic." }, { type: "h2", text: "What local training covers" }, { type: "p", text: "Sending organizations also teach care-specific vocabulary so workers are ready to contribute as soon as they arrive in Japan." }] },
    ne: { title: "विशेष दक्षता (स्याहार) का लागि चाहिने जापानी स्तर", excerpt: "जापानी आवश्यकता (JLPT N4・JFT-Basic) र स्थानीय तालिम व्याख्या।", lead: "JLPT N4・JFT-Basic आवश्यकता र देशभित्रको तालिमबारे व्याख्या।", body: [{ type: "p", text: "विशेष दक्षता (स्याहार) का लागि N4 वा माथि, वा JFT-Basic उत्तीर्ण आवश्यक छ।" }, { type: "h2", text: "स्थानीय तालिमले समेट्ने" }, { type: "p", text: "पठाउने संस्थाले स्याहार विशिष्ट शब्दावली पनि सिकाउँछन्, जसले गर्दा जापान पुग्नेबित्तिकै काम गर्न तयार हुन्छन्।" }] },
  },
  "partnership-start": {
    vi: { title: "Thông báo khởi động hợp tác Momokichi × ITM Japan", excerpt: "Chuyên gia điều dưỡng và cơ quan hỗ trợ đăng ký hợp tác, khởi động dịch vụ giới thiệu nhân lực.", lead: "Chuyên gia điều dưỡng và cơ quan hỗ trợ đăng ký hợp tác, khởi động dịch vụ giới thiệu nhân lực Nepal.", body: [{ type: "p", text: "Công ty CP Momokichi và ITM Japan hợp tác, khởi động dịch vụ「Nepal Kaigo Jinzai Navi」." }, { type: "p", text: "Kết hợp thế mạnh của Momokichi am hiểu hiện trường và ITM Japan có giấy phép, mang đến nhân lực chắc chắn cho các cơ sở." }] },
    en: { title: "Announcing the Momokichi × ITM Japan partnership", excerpt: "Care professionals and a registration support org join forces to launch a staffing service.", lead: "Care professionals and a registration support organization launch a Nepali staffing service.", body: [{ type: "p", text: "Momokichi Co., Ltd. and ITM Japan have partnered to launch the “Nepal Kaigo Jinzai Navi” service." }, { type: "p", text: "Combining Momokichi's on-the-ground expertise with ITM Japan's licensing, we deliver reliable talent to facilities." }] },
    ne: { title: "Momokichi × ITM Japan सहकार्य सुरुको सूचना", excerpt: "स्याहार विशेषज्ञ र दर्ता सहयोग संस्था मिलेर जनशक्ति सेवा सुरु।", lead: "स्याहार विशेषज्ञ र दर्ता सहयोग संस्था मिलेर नेपाली जनशक्ति सेवा सुरु।", body: [{ type: "p", text: "Momokichi कम्पनी र ITM Japan मिलेर “नेपाल केयर जनशक्ति नेवी” सेवा सुरु गरेका छन्।" }, { type: "p", text: "क्षेत्रको अनुभव भएको Momokichi र अनुमति भएको ITM Japan को बल मिलाएर केन्द्रहरूलाई भरपर्दो जनशक्ति।" }] },
  },
  "support-after-arrival": {
    vi: { title: "Hỗ trợ định cư sau khi sang Nhật làm được gì", excerpt: "Hướng dẫn cuộc sống, thủ tục hành chính, phỏng vấn định kỳ — nội dung hỗ trợ của cơ quan hỗ trợ đăng ký.", lead: "Giới thiệu nội dung hỗ trợ của cơ quan hỗ trợ đăng ký sau khi nhân lực sang Nhật.", body: [{ type: "p", text: "Cơ quan hỗ trợ đăng ký đảm trách 10 hạng mục hỗ trợ như tìm nhà ở, hướng dẫn cuộc sống và phỏng vấn định kỳ." }, { type: "p", text: "Momokichi và ITM Japan hỗ trợ theo kiểu đồng hành cùng cả cơ sở và nhân lực." }] },
    en: { title: "What post-arrival retention support can do", excerpt: "Life orientation, administrative procedures, regular check-ins — what registration support covers.", lead: "An overview of the support a registration support organization provides after arrival.", body: [{ type: "p", text: "A registration support organization handles ten support items, including housing, life orientation, and regular interviews." }, { type: "p", text: "Momokichi and ITM Japan provide hands-on support that walks alongside both facility and talent." }] },
    ne: { title: "आगमनपछिको बसोबास सहयोगले के गर्न सक्छ", excerpt: "जीवन अभिमुखीकरण, प्रशासनिक काम, नियमित भेटघाट — दर्ता सहयोगले समेट्ने।", lead: "आगमनपछि दर्ता सहयोग संस्थाले दिने सहयोगको परिचय।", body: [{ type: "p", text: "दर्ता सहयोग संस्थाले आवास, जीवन अभिमुखीकरण र नियमित भेटघाटसहित १० वटा सहयोग सम्हाल्छ।" }, { type: "p", text: "Momokichi र ITM Japan ले केन्द्र र जनशक्ति दुवैसँगै रहने सहयोग दिन्छन्।" }] },
  },
  "facility-count-30": {
    vi: { title: "Số cơ sở hợp tác đã vượt 30", excerpt: "Hợp tác với cơ sở điều dưỡng toàn quốc đã vượt 30. Kèm cơ cấu theo vùng.", lead: "Số cơ sở hợp tác toàn quốc đã vượt 30.", body: [{ type: "p", text: "Tập trung ở Kanto・Kansai, số cơ sở hợp tác đã vượt 30. Chúng tôi sẽ tiếp tục mở rộng ra toàn quốc." }] },
    en: { title: "We've passed 30 partner facilities", excerpt: "Partnerships with care facilities nationwide have surpassed 30, with a regional breakdown.", lead: "Our nationwide partner facilities have surpassed 30.", body: [{ type: "p", text: "Centered on the Kanto and Kansai regions, partner facilities have passed 30. We will continue expanding nationwide." }] },
    ne: { title: "साझेदार केन्द्र ३० नाघ्यो", excerpt: "देशभरका स्याहार केन्द्रसँगको साझेदारी ३० नाघ्यो। क्षेत्रगत विवरणसहित।", lead: "देशभरका साझेदार केन्द्र ३० नाघेका छन्।", body: [{ type: "p", text: "कान्तो・कान्साई केन्द्रित, साझेदार केन्द्र ३० नाघ्यो। आगामी दिनमा देशभर विस्तार गर्नेछौं।" }] },
  },
  "interview-osaka": {
    vi: { title: "Một ngày của nhân viên làm việc tại cơ sở Kansai", excerpt: "Từ giao ca buổi sáng đến chăm sóc người sử dụng — theo chân một ngày của nhân lực Nepal.", lead: "Theo chân một ngày của nhân lực Nepal, từ giao ca sáng đến chăm sóc.", body: [{ type: "p", text: "Bắt đầu bằng giao ca buổi sáng, hỗ trợ ăn uống・tắm rửa・hoạt động giải trí. Một ngày tràn ngập nụ cười." }] },
    en: { title: "A day in the life of staff at a Kansai facility", excerpt: "From the morning handover to resident care — a day with a Nepali staff member.", lead: "We followed a day in the life of a Nepali staff member, from the morning handover to care.", body: [{ type: "p", text: "Starting with the morning handover, supporting meals, bathing, and recreation. A day full of smiles." }] },
    ne: { title: "कान्साई केन्द्रमा कार्यरत कर्मचारीको एक दिन", excerpt: "बिहानको ह्यान्डओभरदेखि सेवाग्राही स्याहारसम्म — नेपाली कर्मचारीको एक दिन।", lead: "बिहानको ह्यान्डओभरदेखि स्याहारसम्म, नेपाली कर्मचारीको एक दिनको झलक।", body: [{ type: "p", text: "बिहानको ह्यान्डओभरबाट सुरु, खाना・नुहाउने・मनोरञ्जन सहयोग। मुस्कानले भरिएको एक दिन।" }] },
  },
  "new-year-greeting": {
    vi: { title: "Lời chúc năm mới và hoạt động năm nay", excerpt: "Năm nay cũng lấy「nhân lực chắc chắn」làm lý niệm, trở thành cầu nối cơ sở và nhân lực.", lead: "Năm nay cũng lấy「nhân lực chắc chắn」làm lý niệm, trở thành cầu nối cơ sở và nhân lực.", body: [{ type: "p", text: "Cảm ơn sự ưu ái trong năm qua. Năm nay chúng tôi sẽ tiếp tục nỗ lực giới thiệu nhân lực một cách trung thực." }] },
    en: { title: "New Year's greeting and this year's initiatives", excerpt: "Guided by “reliable talent,” we will continue to bridge facilities and people this year.", lead: "Guided by the ideal of “reliable talent,” we will continue to bridge facilities and people.", body: [{ type: "p", text: "Thank you for your support last year. This year we will continue to strive for honest, dependable placement." }] },
    ne: { title: "नयाँ वर्षको शुभकामना र यस वर्षको पहल", excerpt: "यस वर्ष पनि “भरपर्दो जनशक्ति” आदर्शमा, केन्द्र र जनशक्तिको पुल।", lead: "यस वर्ष पनि “भरपर्दो जनशक्ति” आदर्शमा, केन्द्र र जनशक्तिको पुल बन्नेछौं।", body: [{ type: "p", text: "गत वर्षको सहयोगका लागि धन्यवाद। यस वर्ष पनि इमानदार र भरपर्दो परिचयमा लाग्नेछौं।" }] },
  },
};
